version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  web: # 해당 프로젝트 내의 웹 애플리케이션 컨테이너
    build: .
    container_name: realtime-webchat
    depends_on: # redis가 먼저 돌아가게 하기 위함
      - redis
    ports:
      - '8080:8080'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    command: ["python", "app/server.py"]
